name: inventory_app_final
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  fl_chart: ^0.69.2
  charts_flutter_new: ^0.12.0
  intl: ^0.17.0
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  google_fonts: ^6.2.1
  syncfusion_flutter_charts: ^21.2.4
  flutter_slidable: ^3.1.2
  slide_action: ^0.0.2
  slide_to_act: ^2.0.2
  lottie: ^3.3.0
  convex_bottom_bar: ^3.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/Galaxy_6_Shoes_Black_GW3847_01_standard.jpeg
    - assets/-473Wx593H-466060513-black-MODEL.jpg
    - assets/images/123-joyride-cdp-apla-xa-xp.jpg
    - assets/images/28829132.jpg
    - assets/images/Invento.png
    - assets/Untitled design.png
